<?php
// TODO:  Change PAGE TITTLE
// TODO:  Add keywords and description
?>
<!-- All the stylesheet elements -->
<?php include 'includes/header.php'; ?>
<!--  END-->

<meta name="keywords" content="HTML5 Template" />
<meta name="description" content="Slander - Responsive HTML5 Landing Page">


<title>Publications: Genetic Analogies</title>


</head>

<body id="page-top">

  <!-- Outer-wrap -->
  <div class="outer-wrap">
    <div class="container">

      <!-- Fixed Left Navigaton -->
      <?php include 'includes/vertical_navbar.php'; ?>
      <!-- Fixed Left Navigaton END-->

      <!-- Right Main Content -->
      <div class="col-md-9 m-right">


        <!-- Blog Post Content -->
        <div class="row" data-animated="0">
          <div class="col-md-12">
            <div id="m-blog-content">
              <div class="row">
                <div class="col-md-12">
                  <article class="item">
                    <div class="mb-thumb">
                      <img src="img/blog/1-big.jpg" class="img-responsive" alt=""/>

                    </div>
                    <!-- #BeginEditable "PageContent" --><h4>Understanding &amp; Teaching Genetics Using Analogies<br />
                    </h4>
                    <h5>Scott Woody and Ed Himelblau</h5>
                   <h6>The American Biology Teacher, Vol. 75, No. 9, pages 664–669. ISSN 0002-7685, electronic ISSN 1938-4211. ©2013 by National Association of Biology Teachers. All rights reserved.</h6>
                   <p><em>Additional Resources, including downloadable pdf versions, powerpoint slides, and colored figures are available <a href="publication_genetic_analogies_resources.php">here</a></em></p>
                   <p><strong>Abstract</strong>: A  collection of analogies is presented that are intended to help students better  understand the foreign and often nuanced vocabulary of the genetics curriculum.  Why is it called the wild type? What is the difference between a locus, a gene,  and an allele? What is the functional (<em>versus </em>a rule-based) distinction between dominant and recessive alleles? It is our  hope that by using these analogies teachers at all levels of the K-16  curriculum can appeal to the common experience and common sense of their  students to lay a solid foundation for mastery of genetics and, thereby, to  enhance understanding of evolutionary principles.</p>
                   <p> <strong>Key words: </strong>Genetics,  analogies, locus, allele, dominant, recessive<strong></strong></p>
                 <p>As famously written in the pages of this very journal some  60 years ago, &ldquo;Nothing in biology makes sense except in light of evolution&rdquo;.  Given that the science and language of genetics is key to understanding  evolution, and evolution is the key to understanding biology, we will argue  that building a strong foundation based on a clear understanding of terms used  in genetics education is essential for effective student education in biology.</p>
                   <p>There are two significant challenges  facing both teachers and students in the course of the genetics &ldquo;unit&rdquo; in the  biology curriculum. First, many of the terms used repeatedly in genetics have  no common usage outside of that realm. There is no &ldquo;real world&rdquo; situation in  which terms like heterozygote or genotype&mdash;or for that matter allele and  locus&mdash;are used. It really is as if students are being asked to learn a foreign  language with all the attendant challenges that may entail. Second, many  genetic terms are defined in opposition to similar-sounding terms whose  meanings are quite distinct: genotype <em>versus </em>phenotype; heterozygous <em>versus </em>homozygous,  dominant <em>versus </em>recessive, and wild  type <em>versus </em>mutant. It seems nearly  certain that if students don&rsquo;t understand one of those paired terms then they  surely cannot understand the other.</p>
                   <p>In our teaching experience in both  laboratory and classroom settings, we have witnessed the power of an apt  analogy to help students understand the vocabulary of genetics.&nbsp; In what follows we will describe several we believe  to be particularly effective in helping students gain a lasting comprehension  of this fundamental biological science. We readily admit at the outset that our  belief in their utility rests on intuition that has been bolstered by  interactions with both students and teachers alike. We will confess, further, that  the analogies on offer here have no grounding in cognitive sciences research; they  are simply approaches we have developed and believe to be useful. They are  offered &ldquo;as is&rdquo; and in what we hope is a conversational and accessible style  that is of use to readers of ABT.</p>
                   <p> <strong>1. Locus <em>versus </em>gene</strong>: &ldquo;Locus&rdquo; (from the Latin <em>place</em>; plural <em>loci</em>) refers to the physical site of a particular genetic element  along a chromosome. &ldquo;Gene&rdquo; can be synonymous with &ldquo;locus&rdquo;. The distinction is  subtle but essentially reflects what is known about the &ldquo;particular genetic  element&rdquo;, a phrase in the definition that is deliberately vague. Specifically,  if all we know is that a mutation exists which causes a perceptible change in  the phenotype of an organism upon transmission to progeny generations it is  best to use &ldquo;locus&rdquo;, as that usage does not imply that we know much or anything  about the molecular mechanism(s) by which the phenotypic effects come about.  Use of the term &ldquo;gene&rdquo; becomes appropriate when we have investigated the locus  to understand the functional role of associated DNA sequences. Thus, &ldquo;gene&rdquo;  refers to all protein coding sequences as well as regulatory elements that  govern expression of the encoded function.</p>
                   <p>A straightforward analogy useful to  explain the difference between loci and genes is as street addresses. Imagine a  fictional small town named Rustic (upper panel, Figure 1). We might say &ldquo;There  is an occupied lot at 267 Main Street&rdquo;. This doesn&rsquo;t tell us anything other  than the fact that there is a building of some sort at that address that does  something of consequence (locus). However, if we know that it&rsquo;s a business,  that it sells prepared foods and it&rsquo;s a place called &ldquo;Good Eats&rdquo;, we explicitly  assert that we have considerably more knowledge of many things regarding the  structure and activities at 267 Main Street, perhaps including the quality of  the food, the likelihood of getting a table during the dinner hour, the price  of entrees, <em>etc</em>. That is, we can be  much more specific and authoritative in our choice of vocabulary (gene).</p>
                   <p><strong>2. Locus <em>versus</em> allele</strong>: Unlike the nearly synonymous terms &ldquo;locus&rdquo; and  &ldquo;gene&rdquo;, &ldquo;locus&rdquo; and &ldquo;allele&rdquo; have decidedly different meanings. In genetics  terminology, &ldquo;allele&rdquo; is used to refer to a DNA sequence that differs from an  alternative DNA sequence that might instead occupy<em> the same locus.</em> Please note that the particular DNA sequence  difference that distinguishes between alternative alleles may or may not have  functional consequences on the encoded product or genetic function and thereby  affect the phenotype of an individual; the mere existence of such differences  is sufficient to constitute alternative allelic forms&mdash;provided that they occupy  the same chromosomal location (locus). Expanding on the small town analogy  introduced above, let&rsquo;s imagine that the town of Rustic lies just north of a  very similar small town named Desolation (lower panel, Figure 1). &nbsp;Imagine that  both Rustic and Desolation were originally cookie-cutter replicas of planned  communities drawn from the same master plan by the county planning commission.  Driving into either town on Main Street takes us through a residential area  sporting modest homes and then into the business district with shops, banks,  gas stations and restaurants&mdash;typical small town fare.</p>
                   <div class="figure imgcenter"><img class="img-responsive" src="assets/img/index_image002.jpg" alt="Woody Figure 1 color.png" /><br />
                     Figure 1:  Lots along Main Street in the fictional small towns Rustic and Desolation. <br /></div><br />
                     <p>Observant travelers might initially  be struck by the similarity of Rustic and  Desolation: homes in the 100 block of Main Street in both towns are of the same  size, shape, and color, and even the business districts are similar, although  not identical. That is, the 200 block in both towns have a gas station, a movie  theater and then a restaurant. However, whereas the movie theaters are the  same, the gas stations and restaurants are of different kinds. A more striking  difference is evident at 321 Main Street: in Rustic there is a bank whereas at  the same address in Desolation there is another gas station.</p>
                     <p>Let&rsquo;s abandon the travelogue and  return to the analogy relating to loci and alleles. Lot 125 Main Street as well  as 173, 211, 245, and 267 Main Street (loci) are, in pair-wise comparisons,  allelic. The homes and the movie theater at 245 Main Street are identical and  so do not constitute <em>alternative</em> alleles but they can be considered allelic (put Rustic and Desolation together  as a pair and you have the equivalent of the homozygous condition). The gas  stations at 211 Main Street and the restaurants at 267 Main Street are not  identical but they serve essentially the same function and so, too, can be  considered as allelic forms (in heterozygous condition). What are we to make of  the lot at 321 Main Street, at which Rustic has a bank and Desolation has  another gas station? If we accept the premise that both towns were designed  from the same master plan this difference may seem a bit perplexing, but a  reasonable evolutionary scenario can be imagined that plausibly explains the  disparity. Just as the gas stations and restaurants in the 200 block have  diverged since the towns were founded, other lots in Rustic and Desolation have  experienced their own evolution over time. Perhaps the bank in Desolation  failed at some point and, after a period in which the remains of the building decayed  and ultimately collapsed, a new business formed on the same lot at 321 Main  Street&mdash;in this case, a new gas station, the same as the old gas station at 211  Main Street in Rustic. Are the establishments at 321 Main Street addresses  allelic? The answer is no: there is no structural or functional similarities  between a bank and a gas station, so even though they share the same address,  the ultimate test of allelism is functional similarity, so the establishments  at 321 Main Street do not fit the bill. Are the gas stations in Rustic and  Desolation allelic? No, they reside at different addresses (loci). That  conclusion begs one last question that I will leave to the readers (and  hopefully their students) to decide: Are the gas stations at 211 Main Street in  Rustic and at 321 Main Street in Desolation allelic?</p>
                   <p><strong>3. Wild type <em>versus </em>mutant alleles</strong>: A common  point of confusion for students learning genetics is to understand what is  meant by the label &ldquo;wild type&rdquo;, as often casually applied to both phenotypes  and genotypes without clear definition. Let&rsquo;s cover &ldquo;wild type&rdquo; (<em>wt</em>) first and then turn to an analogy to  help students appreciate the distinction between <em>wt </em>and mutant alleles. As geneticists, we typically select a particular  animal, plant, or other organism to serve as prototype of the kind. &ldquo;Model&rdquo;  organisms such as <em>Drosophila</em> <em>melanogaster </em>(insects, metazoans), <em>Arabidopsis thaliana </em>(flowering plants),  or <em>Caenorhabditis elegans </em>(nematodes) have  been selected as common objects of study in expectation that what we learn  through research on those model organisms will be broadly applicable to explain  biological processes in related species. A secondary but very important  consideration influencing the selection of model organisms is to determine which  organisms are experimentally tractable: do we have the tools available to  advance our research?</p>
                     <p>An analogy I have found useful to help  students appreciate why we study fruit flies, weeds that grow in sidewalk  cracks, or small worms that grow in soil, is to ask them to imagine being a  space alien just landed on planet earth. Looking around from the center of New  York City, our alien selves notice that among the many things in this foreign  environment are automobiles of varying shapes and sizes. Our innate curiosity compels  us to try to understand how cars work, but given the wide range of alternative  models available, studying all models is neither feasible nor possible given  limited resources. Thus, the first choice we face is &ldquo;Which car model should we  study&rdquo;? One answer might be to select the Lamborghini, a very expensive and  relatively rare model, but surely an exceptionally spectacular automobile; an  alternative might be to select a Toyota Camry, a fine but common and somewhat  unexceptional model.</p>
                   <p>Which  should we choose? Clearly it is the Camry: its design and operating features  are shared in common with many other cars that we see on the road and both  tools and repair parts are readily available. Most importantly, what we learn  by study of a Camry seems likely to apply to Corollas, Chevrolets and perhaps  even Saabs; it is doubtful that studying a Lamborghini could yield similarly  generalizable results.</p>
                     <p>Would study of a Camry necessarily imply that  all of its parts and operating features are optimal forms relative to all other  cars? The obvious answer is no: What we learn from a focused study of the Camry  merely establishes a model for how a common automobile or its subsystems  operate. As our studies expand to include other models and brands, we will  likely find both similarities and differences, and some of the latter may prove  to be superior or inferior to those incorporated into the design of a Camry.  Here, then, the Camry serves merely as a reference type, just as a &ldquo;wild type&rdquo;  Arabidopsis plant of the <em>Columbia</em> variety has served as a well-studied  model of flowering plants. </p>
                   <div class="figure" style="width:300px; float:left"><img class="img-responsive" src="assets/img/index_image004.jpg" hspace="12" alt="young alb unlabeled.png" /><p>Figure 2: The recessive FPsc albino mutant allele prevents elaboration of the photosynthetic machinery yellow segregants among the F2s shown above) if present in homozygous condition</p></div>
                   <p>4. Dominant <em>versus </em>recessive  alleles</strong>: Now  let us turn to another bugaboo of genetics vocabulary- the relationship between  dominant and recessive alleles. Many students have a rather superficial,  rule-based understanding of the distinction between dominant and recessive  alleles: Dominant alleles are those whose effect on phenotype is evident when  present in a single copy; conversely, recessive alleles must be present in  homozygous condition in order to produce a detectable change in organismal  phenotype as compared to that of the (phenotypically) wild type individual.  Those rules certainly apply, but fail to convey any sense of the molecular  basis for <em>why</em> those rules exist in the first place. To lay the  groundwork for the analogy that follows, recognize that mutant alleles arising  spontaneously through errors in DNA replication or damage repair processes, or  mutant alleles that result from chemical mutagenesis of the reference <em>wt </em>genome  typically yield what geneticists refer to as &ldquo;loss of function&rdquo; alleles, where  the coding potential of the locus has been altered in a way that no functional  gene product can be produced from the altered DNA template&mdash;say, introduction of  a stop codon in a protein coding gene. In most cases, recessive alleles have  little or no effect on phenotype since the remaining <em>wt </em>allele in  heterozygotes can suffice to provide the required function, but if present in  the homozygous state the near or total lack of functioning gene product may  impose phenotypic consequences upon such individuals that lack the wild type or other functional allele. The FPsc <em>albino </em>mutant allele is a good  example of a simple recessive allele (Figure 2). In a segregating F2 population  as shown, &frac14; of individuals in the population are unable to properly elaborate  the photosynthetic machinery and so grow as weakly pigmented (yellow/white)  seedlings. While we do not yet know the precise molecular basis of the <em>albino</em> phenotype, the recessive nature of the mutant allele as compared to the <em>wt </em>alternative  makes it nearly certain that the <em>albino</em> mutation has disrupted a locus  that is absolutely essential in order for plants to &ldquo;be&rdquo; green.</p>
                 <p>On the other hand, dominant alleles often  result from &ldquo;gain of function&rdquo; mutations whose effects are evident even if  present in just a single copy. As a hypothetical example, imagine a mutation  that alters the substrate specificity of a key metabolic enzyme such that the  encoded gene product enables the organism to harvest energy from an additional  carbohydrate source in its environment&mdash;for example, let&rsquo;s say an organism  carrying the mutant allele, expressed in precisely the same tissues and at the  same level of expression as its <em>wt </em>counterpart can digest both glucose <em>and </em>sucrose, while those individuals carrying only the wild type allele must  live on glucose alone. If sucrose is plentiful in the environment and carbon  sources are growth-rate limiting, the heterozygote will likely enjoy a fitness  advantage over the wild type homozygote.</p>
                   <div class="figure" style="width:300px; float:left"><img class="img-responsive" src="assets/img/index_image008.gif" hspace="12" alt="Adobe Systems" />
                   <p>Figure 3: The dominant FPsc ale mutant allele causes pronounced leaf curling</p></div>
                   <p>Alternatively, dominant alleles may arise via  mutations that alter the temporal or spatial pattern of gene expression. The  dominant FPsc <em>abnormal leaf </em>(<em>ale</em>) allele is a case in point  (Figure 3). The <em>ale </em>locus encodes a &ldquo;master&rdquo; regulatory factor that  governs allocation of cell types in the course of leaf development between  those that serve evolved functions and reside on the upper (adaxial) leaf  surface and those that differentiate to serve the functions of cells that  occupy lower (abaxial) tissues in mature leaves. Proper allocation of adaxial  and abaxial cell types is essential for formation of the flat solar panels we  recognize as leaves. Misallocation/overproliferation of primordial cells into  one class over the other during leaf development results in formation of curled  leaves. Fascinating though they may be, we need not go further into the  molecular details of the <em>ale </em>mutant phenotype here; it is sufficient to  note that dominant mutant alleles can have effects even if present in single  copy, since it only takes &ldquo;one bad apple&rdquo; to perturb the developmental fate of  cells during organ formation.</p>
                     <p>To help students to better appreciate (and care about!) the molecular  basis that distinguishes between loss-of-function recessive alleles and  gain-of-function dominant alleles, I have used the following analogy to good  effect with both students and teachers:</p>
                     <blockquote>
                       <p><em>Imagine a symphony orchestra that intends to play a piece that includes a  soaring violin solo that is the musical climax of the work. Imagine, further,  that each bit of sheet music provided to the assembled musicians calls for two  players of each part: two violin soloists, two oboe parts, two tympanist  scores, etc. Now, during that violin &ldquo;solo&rdquo; passage, the orchestral score  directs the tympanis to observe a 60 measure rest while the twin first-chair  violinists bring the listening audience to tears (Figure 4, panel A).</em>  </p>
                       <p><em>What if the sheet music for one of those violinists had been garbled to  the point of uselessness during the printing process, an error that had gone  unnoticed until the evening of the performance? &nbsp;Unable to perform, the violinist with unreadable  sheet music would effectively be silenced, but the violinist with the proper sheet music could continue  nonetheless, playing a bit louder if necessary to achieve the desired and  dramatic effect; the &ldquo;phenotype&rdquo; of the movement would likely be little changed  (Figure 4, panel B). However, if both violinists&rsquo; sheets were similarly garbled  and neither had memorized the passage, nearly all is lost: the musical piece  fails to reach its emotional crescendo and the phenotype has changed decidedly  for the worst (Figure 4, panel C).</em></p>
                     </blockquote>
                     <div class="figure imgcenter"><img class="img-responsive" src="assets/img/index_image010.jpg" alt="Figure 4 color composite.png" />
                     <p>Figure 4:&nbsp; Musical Mutations.&nbsp; A) With all sheet music printed correctly the  violins play while the tympani rest.&nbsp; B)  Garbled sheet music prevents one violin from performing, however the second  violin can perform and the piece proceeds.&nbsp;  This represents a heterozygous genotype in which the functional (wildtype) allele is  dominant over a recessive, loss-of-function allele. &nbsp;C) If the sheet music  for both violins is garbled, the piece cannot be performed. &nbsp;This  represents a homozygous recessive genotype. &nbsp;D) The sheet music for the  violins is correct, however, one tympani score is garbled prompting the  tympanist to play when he should rest. &nbsp;Even though one tympani has the  correct (wildtype) score a single mutant copy of the score is sufficient to  disrupt the performance. &nbsp;This is analogous to a dominant,  gain-of-function mutation.</p></div>
                     <p>The preceding neatly illustrates the practical consequence of most  recessive, loss-of-function mutant alleles: as long as a good copy of the locus  remains available (as in the heterozygous condition) there may be little or no  effect on phenotype, but if no functional copy of the locus is available, as  would be the case in the homozygous condition, the phenotypic effects of that  loss-of-function may be manifest.</p>
                     <blockquote>
                       <p> <em>Now imagine that the printing company charged with producing sheet music  for the various musicians in the orchestra was, well, just really bad at the  job. Specifically, imagine that of the two pieces of sheet music distributed to  the tympanists, one properly indicated a 60 measure rest during the violin solo  but the other had a typo that, instead, specified merely a 6 measure rest.  Suddenly, and just as the violin solo begins to soar, the  percussionist&mdash;dutifully following his or her errant instructions&mdash;breaks in,  with the result that all music that follows is arrhythmic and discordant. Even  though the second tympanist properly remained silent, the musical performance  was doubtlessly altered, and probably for the worse; the phenotype had changed  and all it took was one altered bit of encoded information (Figure 4, panel D).</em> </p>
                     </blockquote>
                 <p>This last bit nicely models the phenotypic consequences  affecting leaf development in the FPsc <em>ale</em> mutant: misexpression of the locus whose activity is controlled, at least in  part, by the regulatory sequence altered in the dominant <em>ale</em> mutant allele has profound downstream developmental  consequences.</p>
                     <p><strong>5. DNA as a musical  score, <em>NOT </em>a blueprint</strong>: The preceding brings us to the last analogy we wish  to present. Many biology teachers make use of analogies in many different  contexts, but when it comes to genetics and the role of DNA as the mechanism by  which evolved information is both stored and expressed, many turn to the  ever-popular &ldquo;DNA as the blueprint of life&rdquo;. To do so is understandable, if for  no reason than the fact that it is the analogy frequently used in most print  and visual media reports that appear in the press. However, the analogy fails  spectacularly to convey to our students the role of DNA.</p>
                     <p>To wit, a blueprint is essentially  a two-dimensional representation of three dimensional objects that are intended  to be produced. If one looks at the blueprint for a room or a house it is  almost immediately apparent what those entities will look like and what  functions they will serve: an entryway here, a window there, and a bathroom in  the corner, <em>etc.</em> However, DNA  sequences in the raw form of A&rsquo;s, C&rsquo;s, G&rsquo;s, and T&rsquo;s carry no such implications  regarding either form or function of the encoded element. To imply otherwise by  invoking a blueprint analogy plants the image of genes on a chromosome as  somehow resembling in form and function the product or activity they encode and  nothing could be further from the truth of the matter.</p>
                     <p>DNA sequences that comprise the  genome of an organism or species can much more usefully be analogized as the  complete orchestral score carried by the maestro to the podium prior to the  intended musical performance. Each note (nucleotide) and each piece of sheet  music (gene) instructs the performers on how to produce the intended melodic  outcome (the phenotype, as expressed from the genotype as encoded in musical  notations of half-notes, chords, rests, <em>etc</em>.).&nbsp; Excepting those who are preternaturally able  to &ldquo;hear&rdquo; the music by inspection of the complete score as indicated on the  sheet music, a bit of translation and elaboration is required before the  performance and expression of the musical phenotype becomes apparent. Beyond  the fact that it is considerably more apt than a blue print analogy, the DNA as  musical score analogy has the additional virtue of injecting a dynamic sense to  patterns of gene expression and the arrangement of biological processes that  program growth and development. It is also quite flexible and may be extended  as you prefer to include notions of harmonic interplay among different musical  sections. </p>
                     <p> Finally, and assuming that the  reader accepts the musical score analogy, the analogy can be extended even  further to incorporate epigenetic mechanisms: <em>adagio, pianissimo</em>, <em>allegro&hellip;</em> are all musical notations imposed over raw musical scores (nucleotide  sequences) to indicate the pace or volume with which the encoded notes are to  be expressed; it is by now well-established that various modifications to DNA  bases or to associated histone proteins can have significant influence over  expression of the native DNA sequence. As a final embellishment to complete the  analogy, one could point out to students the feedback loops that exist between  musicians and the audience (the environment). This is a much richer, more vivid  and more evocative analogy than the essentially static and erroneous view of  the genome as portrayed by using the blueprint analogy.</p>
                     <p> <strong>Conclusion</strong>: It is  our hope that the analogies presented herein might be useful to teachers in  order to help their students to master the vocabulary and vernacular of genetic  science. Just as mastery of a second language can be advanced by a &ldquo;total  immersion&rdquo; experience gained by travelling abroad, so too can mastery of  genetics be advanced by constant usage and attention to nuance of the  associated vocabulary. It must be noted that all analogies, as abstractions  from the primary subject of interest, will inevitably break down if taken to  logical extremes. For example, and with particular reference to the car  analogy, what would it mean if, say, the stereo of a BMW was deemed &ldquo;superior&rdquo;  to that of the Camry? Does that translate to a dominant/recessive relationship?  We will withhold judgment on this call except to note that extending the  analogy to consider the point could be useful to help our students to  appreciate that dominance relationships between alleles are meaningful only in  a pair-wise comparison of function in a common circumstance. In any case, we  would consider it &ldquo;mission accomplished&rdquo; if use of any of the preceding analogies  prompted objection from your students who might recognize the breaking point at  which they become inapt.</p>
                     <p>A recurrent theme within the  analogies we suggest here is an attempt to clarify the sometimes nuanced  distinctions between alleles and loci, and between wild type, dominant and  recessive alleles. This emphasis is entirely intentional and also timely. A  common theme of the Next Generation Science Standards and revised AP Biology  curriculum is the centrality of evolution to all areas of biological study.  Evolution may be broadly defined as the change in allele frequencies within a  population over time. That definition usefully encompasses both of the major  drivers of evolutionary change: natural selection and genetic drift, and quite  properly emphasizes allelic differences as the primary agents through which  evolutionary processes operate. We trust it is self-evident that a clear  understanding of what an &ldquo;allele&rdquo; is would be useful to help our students grasp  the larger picture and hope that the approaches advocated here can advance our  mutual goals for more effective genetics education in particular and biology  education, in general.</p>
                       <p>Acknowledgements: <em>This  manuscript and the continuing development of FPsc resources for genetics  education have been supported by funding from the National Science Foundation  and the Howard Hughes Medical Institute through grants awarded to Rick Amasino,  University of Wisconsin-Madison.</em>  </p>
                   <!-- #EndEditable -->

</div></div></div></div></div>
                    <!-- Script and footer -->
                    <?php include 'includes/footer.php'; ?>
                    <!--  Script and footer END-->
